// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceMode = "system" | "light" | "dark";

export type Block = { kind: string, text: string, byte_range: [number, number], };

export type Document = { path: string | null, contents: string, dirty: boolean, };

export type FileNode = { name: string, path: string, is_dir: boolean, children: Array<FileNode>, };

export type OutlineEntry = { level: number, text: string, byte_offset: number, };

export type ParsedDoc = { blocks: Array<Block>, };

export type Settings = { theme: Theme, appearance: AppearanceMode, font_size_px: number, };

export type Theme = "smoke" | "amber";
