// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Block = { kind: string, text: string, byte_range: [number, number], };

export type Document = { path: string | null, contents: string, dirty: boolean, };

export type ParsedDoc = { blocks: Array<Block>, };
